# Generated by Django 5.2.3 on 2025-07-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_project_description_project_descriptions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Inp Progress", "IN_PROGRESS"),
                    ("Completed", "COMPLETED"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
