# Generated by Django 5.2.3 on 2025-07-03 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskdetails",
            name="assigned_to",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("In Progress", "IN_PROGRESS"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="taskdetails",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="tasks.task",
            ),
        ),
    ]
