# Generated by Django 5.0.1 on 2025-07-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_remove_taskdetails_assigned_to_alter_task_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("Completed", "COMPLETED"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
