# Generated by Django 5.2.3 on 2025-06-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_employee_task_employees"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="employees",
            new_name="assigned_to",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="due_data",
            new_name="due_date",
        ),
        migrations.RenameField(
            model_name="taskdetails",
            old_name="Task",
            new_name="task",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
    ]
