# Generated by Django 5.2.3 on 2025-06-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_rename_first_name_employee_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="description",
            new_name="descriptions",
        ),
    ]
