# Generated by Django 5.0.1 on 2025-07-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_alter_task_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
