# Generated by Django 5.0.1 on 2025-07-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_delete_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("In Progress", "IN_PROGRESS"),
                    ("Completed", "COMPLETED"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
