# Generated by Django 5.0.1 on 2025-07-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdetails",
            name="asset",
            field=models.ImageField(blank=True, null=True, upload_to="task_asset"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("IN_PROGRESS", "In Progress"),
                    ("Completed", "COMPLETED"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
