# Generated by Django 5.0.1 on 2025-07-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdetails",
            name="asset",
            field=models.ImageField(
                blank=True,
                default="task_asset/default_img.png",
                null=True,
                upload_to="task_asset",
            ),
        ),
    ]
